### ISSUE TITLE
Some loadout files are incorrect

### ISSUE THREAD

**Issue by jameslkingsley** [ARCOMM/Loadouts#2]
Anywhere a file starts with the following, will cause issues when using the loadout file in a mission as part of assignGear.

this = _this;

Should just remove it.

**Comment by Jaegerhaus** [comment]
+1
I added that for submission to match the other files! Scratched my head but figured it was a framework thing.

**Comment by edelle** [comment]
Ignore my reopen, but fixed it, thanks guys
